public class TryAndCatch {

	/*
	In Java, all exceptions are represented by classes. When an exception occurs
	in Java, an object of some type of exception class is generated. It is recommended to
	look through Java's documentation for the Throwable class and its subclasses to see what
	exceptions can occur in your programs. Throwable is the superclass of all errors and exceptions in the Java language.
	A way that we can "catch" these exceptions that Java throws is through a try, catch
	block. Consider the following code:
	
	String[] groceries = {"Milk", "Eggs", "Bread"};
	System.out.println(groceries[10]);
	
	If you remember one of the lessons from "arrays", you'll know that this will result in
	an exception, or more accurately, Java generating an IndexOutOfBoundsException object. With
 	a try, catch block, we can put the code that might generate an error within a try block, and the code
 	to run when the exception occurs within a catch block:
 	
 	String[] groceries = {"Milk", "Eggs", "Bread"};
	try {
		System.out.println(groceries[10]);
	} catch(IndexOutOfBoundsException e) { // The type of exception and the object name
		System.out.println("Something went wrong.");
	}
	
	OUTPUT:
	Something went wrong.
	
	Now, the program will continue to run even when an exception occurs. 
	For your challenge, we have created code that will result in an exception being thrown:
	
	int[] myNums = {1, 2, 3};
	System.out.println(myNums[10]);
	
	Use "try catch" to print a custom error message when the exception occurs.
	
	*/
	public static void main(String[] args) {
		//INJECT HERE
		/*
		// DON'T CHANGE THIS CODE
		int[] myNums = {1, 2, 3};
		// ENTER CODE BELOW
		try {
			myNums[10] = 10;
		} catch(IndexOutOfBoundsException e) {
			
		} 
		*/
		
		finally { // TESTING YOUR CODE
			int score = 1;

			String result = score == 1 ? "\nCongratulations!!! You passed the challenge!!! " + score + "/1 Test Cases Passed" : "You have some bugs to fix! " + score + "/1 Test Cases Passed";
			System.out.println(result);
		}


	}

}

